import "./globals.css";
import Provider from "./providers";
import Navbar from "../Components/Navbar";

export const metadata = {
  title: "Groww Stonks",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <body>
      <Provider>
        <Navbar />
        <main>{children}</main>
      </Provider>
    </body>
  </html>
);

export default RootLayout;
